export const AUTH_ERROR_CODES = [
  'AUTH_EMAIL_TAKEN',
  'AUTH_EMAIL_LINKED_TO_PROVIDER',
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_TOKEN_INVALID',
  'AUTH_REFRESH_INVALID',
  'AUTH_SESSION_EXPIRED',
  'SESSION_NOT_FOUND',
] as const;
