export enum ActivityTypeEnum {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_OAUTH_REGISTERED = 'USER_OAUTH_REGISTERED',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED',
  AUTH_METHOD_LINKED = 'AUTH_METHOD_LINKED',
  AUTH_METHOD_UNLINKED = 'AUTH_METHOD_UNLINKED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
}
