export const PLAN_REPOSITORY = Symbol('PLAN_REPOSITORY');
export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const WEBHOOK_EVENT_REPOSITORY = Symbol('WEBHOOK_EVENT_REPOSITORY');
export const PAYMENT_TRANSACTION_REPOSITORY = Symbol('PAYMENT_TRANSACTION_REPOSITORY');
export const SUBSCRIPTION_LIFECYCLE = Symbol('SUBSCRIPTION_LIFECYCLE');
