export const PAYMENT_ERROR_CODES = [
  'PLAN_NOT_FOUND',
  'PAYMENT_PROVIDER_NOT_ENABLED',
  'PAYMENT_NO_SUBSCRIPTION',
  'PAYMENT_PORTAL_UNAVAILABLE',
  'PLAN_PROVIDER_REF_MISSING',
  'PLAN_HAS_SUBSCRIPTIONS',
  'PLAN_PROVIDER_REF_INVALID',
] as const;
